name: 'tg-run-all'

on:
  workflow_dispatch:

env:
  tofu_version: "1.6.0"
  tg_version: "0.57.9"
  working_dir: "run-all"

jobs:

  run:
    runs-on: self-hosted
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2.1.3
        env:
          TRACE: "1"
          TERRAGRUNT_NON_INTERACTIVE: "true"
          INPUT_PRE_EXEC_1: "env"
        with:
          tofu_version: ${{ env.tofu_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: "${{ env.working_dir }}"
          tg_command: run-all plan
          tg_add_approve: 0
