name: 'Terragrunt GitHub Actions'
on:
  workflow_dispatch:

env:
  tf_version: '1.5.7'
  tg_version: '0.53.2'
  working_dir: "run-all"

permissions: write-all

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Plan
        uses: gruntwork-io/terragrunt-action@v2.1.3
        with:
          tf_version: ${{ env.tf_version }}
          tg_version: ${{ env.tg_version }}
          tg_dir: ${{ env.working_dir }}
          tg_command: 'plan'
